### ISSUE TITLE
Enable helm chart test

### ISSUE THREAD

**Issue by Jasstkn** [litmuschaos/litmus-helm#11]
It's better to have some automation tests which has been already written.
I don't know what is your CI service, but we can do it using github actions or something else
https://github.com/helm/chart-testing

**Comment by ksatchit** [comment]
Thats a great thought. Today we use circle CI for doing a basic validation of the charts and push it to gh-pages.

Ref: https://github.com/litmuschaos/litmus-helm/blob/1a38f369b25034729571c7839911bb6175ce3977/.circleci/config.yml#L12

The script does a helm-lint, but I suppose we could add more checks. Also, I suppose we could refine the CI process to use a local script over wget/fetching one from a different repo. 

So, yes would definitely be a value add @Jasstkn !

**Comment by ksatchit** [comment]
Considering most users'flow would be to *install litmus by this chart and visit hub for exp* (Which is what we are suggesting at least) -  I suppose it does make sense to add it here (maybe use different default names for the admin rbac than the ones used in chaos-helm) -- so people don't have to go search for admin-mode rbac in the docs page! 

What do you think @Jasstkn ?

**Comment by Jasstkn** [comment]
> Considering most users flow would be to _install litmus by this chart and visit hub for exp_ (Which is what we are suggesting at least) - I suppose it does make sense to add it here (maybe use different default names for the admin rbac than the ones used in chaos-helm) -- so people don't have to go search for admin-mode rbac in the docs page!
> 
> What do you think @Jasstkn ?

I totally agree with you. It's more convenient.

**Comment by Jasstkn** [comment]
As for CI you can use this:
https://github.com/jaegertracing/helm-charts/blob/master/ct.yaml
https://github.com/jaegertracing/helm-charts/blob/master/.github/workflows/lint-test.yaml

should be pretty similar for CircleCI.

**Comment by ksatchit** [comment]
Cool! Especially like this from the second link. Would be great to add this :) @Jasstkn !! 

````yaml
 - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
```
