### ISSUE TITLE
Configure Ingress for Traefik 1.7 Ingress Controller

### ISSUE THREAD

**Issue by Vr00mm** [litmuschaos/litmus-helm#169]
Hello Traefik users,

Here are values you have to use to make litmus working on Traefik 1.7

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
  host:
    paths:
      frontend: "/"
      server: "/backend"
```
the first annotation tell to kubernetes to use the traefik ingress controller
the second annotation define the rewrite target used for the server calls
https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#general-annotations

Paths have to change too, cause traefik dont deal with (.*)

@Ajesh
