### ISSUE TITLE
[2.5.0] imagePullSecrets not used for internal pods

### ISSUE THREAD

**Issue by glagny** [litmuschaos/litmus-helm#199]
Hi everyone :), when I install the release 2.5.0 (also tested with older version), the `.Values.image.imageRegistryName` is used as prefix for image pull (like for `chaos-operator`, `event-tracker`, `subscriber`, `workflow-controller` pods) but not the `.Values.image.ImagePullSecrets`, the configuration of this part of the values are:

```yaml
image:
  imagePullSecrets:
    - name: <SECRET NAME>
  imageRegistryName: <PRIVATE REGISTRY HERE>/litmuschaos
```

and I still get `ImagePullBackOff` with the good image shape ( like `<PRIVATE REGISTRY HERE>/litmuschaos/litmusportal-event-tracker:2.5.0` for example) but there is no `imagePullSecrets` in the yaml file. Does anyone encounter the problem ? A big thanks in advance !
