### ISSUE TITLE
[Feature] Allow external creation of admin secret

### ISSUE THREAD

**Issue by upstream-dmahlberg** [litmuschaos/litmus-helm#251]
Currently this helmchart forces it's users to put sensitive information into the values.yaml in clear text:

```yaml
adminConfig:
  DBUSER: "admin"
  DBPASSWORD: "1234"
  JWTSecret: "litmus-portal@123"
  VERSION: "2.10.0"
  SKIP_SSL_VERIFY: "false"
  # -- leave empty if uses Mongo DB deployed by this chart
  DB_SERVER: ""
  DB_PORT: "27017"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "litmus"
```

This may lead to users being forced to adapt bad practices, like putting sensitive information into version control software (like git). A great way to bypass this issue would be to set an "existingSecret" property or a flag that allow users to manage this secret outside of helm.
