### ISSUE TITLE
review role/rolebinding when deploying the control center without the self delegate

### ISSUE THREAD

**Issue by jouve** [litmuschaos/litmus-helm#293]
my goal is to deploy the control center in a separate cluster than the cluster where I run the experiments (multiple other cluster).

I configured the helm chart using the following values:
```yaml
  - portalScope: namespace
    adminConfig:
      SKIP_SSL_VERIFY: true
    ingress: 
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      host:
        name: litmus.xxx
        paths:
          frontend: /(.*)
          backend: /backend/(.*)
      tls:
        - hosts:
          - litmus.xxx
    portal:
      server:
        graphqlServer:
          genericEnv:
            SELF_AGENT: "false"
```

since I deploy only the control center, I didn't expect it to need advanced privileges since it's only : mongodb, auth-server, frontend, server.

the install failed with the roles binding (permissions on crd that do not exist, so my non admin user could not grant, etc).

I edited the chart locally , wrapped all of the role/rolebinding in server-role.yaml/server-rolebinding.yaml except `litmus-server-rb-for-{{ include "litmus-portal.fullname" . }}-server`  as per this [comment](https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/server-role.yaml#L286):
```go-template
{{ if eq .Values.portal.server.graphqlServer.genericEnv.SELF_AGENT "true" }}

{{ end }}
# litmus-server-role is used by the litmusportal-server
# If SELF_AGENT=false, then only litmus-server-role and litmus-server-rb are required.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-server-rb-for-{{ include "litmus-portal.fullname" . }}-server

```

and so far, it works :)
