### ISSUE TITLE
Cannot deploy litmus chaoscenter cause of missing securityContext

### ISSUE THREAD

**Issue by Calvinaud** [litmuschaos/litmus-helm#331]
Hello,

We are trying to deploy litmus chaoscenter but the deployment is blocked because there is no securityContext on the "wait-for-mongodb" initContainer used by the server and auth-server.

I tested with the following securityContext and the initContainer was sucessful 
```yaml
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
```
