### ISSUE TITLE
Cannot deploy version 3.0.0

### ISSUE THREAD

**Issue by GeiserX** [litmuschaos/litmus-helm#338]
I'm trying to test helm version 3.0.0. Firstly, I tried upgrading from the latest `2.x` version, but the upgrade was broken because of the migration jobs were failing, even if I didn't have any data on Litmus.

I tried therefore a fresh install but I'm getting:
```
NAME                                         READY   STATUS     RESTARTS   AGE
litmus-portal-auth-server-75cc58864c-74449   0/1     Init:0/1   0          2m
litmus-portal-frontend-6c549d9f54-v5v5v      1/1     Running    0          2m
litmus-portal-mongodb-869c9d8679-fsdcb       1/1     Running    0          2m
litmus-portal-server-cd4c78f66-lm55r         0/1     Init:0/1   0          2m
```

I'm deploying on a test cluster in GKE with sufficient resources.
The `values.yaml` file I'm using is similar to this one:

```

adminConfig:
  JWTSecret: "litmus-portal@12312"
  SKIP_SSL_VERIFY: "false"
  # -- leave empty if uses Mongo DB deployed by this chart
  DBPASSWORD: ""
  DBUSER: ""
  DB_SERVER: ""
  DB_PORT: ""
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "litmus"

image:
  imageRegistryName: litmuschaos

ingress:
  enabled: true
  name: litmus-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: "public"
  host:
    name: "litmus.mydomain.com"
    frontend:
      path: /
      pathType: Prefix
      # pathType: ImplementationSpecific
    backend:
      path: /backend/
      pathType: Prefix
      # pathType: ImplementationSpecific
  tls:
    - secretName: litmus-tls
      hosts:
        - litmus.mydomain.com


portal:
  frontend:
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    updateStrategy: {}
    automountServiceAccountToken: false

    service:
      type: ClusterIP
      port: 9091
      targetPort: 8080

  server:
    replicas: 1
    updateStrategy: {}
    serviceAccountName: litmus-server-account


openshift:
  route:
    enabled: false

# -- Configure the Bitnami MongoDB subchart
# see values at https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
mongodb:
  enabled: true
  auth:
    enabled: true
    rootPassword: "superhardpassword"
    # -- existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, ` mongodb-replica-set-key`)
    existingSecret: ""
  architecture: standalone
  useStatefulSet: false
  replicaCount: 1
  metrics:
    enabled: false
    prometheusRule:
      enabled: false
```
