### ISSUE TITLE
[litmus] mongodb rootPassword is converted to an integer

### ISSUE THREAD

**Issue by wrdls** [litmuschaos/litmus-helm#339]
The default [rootPassword](https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/values.yaml#L338) gets automatically converted to an int by YAML parser libraries.

This makes the env of the post-upgrade-hook Job look like this:

```
          env:
            - name: DB_PASSWORD
              value: 1234
            - name: DB_USER
              value: root
```

Which is not a valid Job because env values need to be strings.

Change the default to something that will always be a string (e.g. `abc123`) or make sure to apply proper quoting with the `| quote` function.

Haven't checked the whole chart but it's at least an issue here: https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/post-upgrade-hook.yaml#L43
