### ISSUE TITLE
[litmus] image litmuschaos/upgrade-agent-cp `3.0.0` missing

### ISSUE THREAD

**Issue by wrdls** [litmuschaos/litmus-helm#340]
Using chart version `3.0.0`

```
  Warning  Failed     6s (x4 over 105s)   kubelet            Failed to pull image "litmuschaos/upgrade-agent-cp:3.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/litmuschaos/upgrade-agent-cp:3.0.0": failed to resolve reference "docker.io/litmuschaos/upgrade-agent-cp:3.0.0": docker.io/litmuschaos/upgrade-agent-cp:3.0.0: not found
```

My workaround is to use the latest beta

```yaml
  upgradeAgent:
    controlPlane:
      image:
        tag: "3.0.0-beta8"
```
