### ISSUE TITLE
Release Charts action fails with '.cr-release-packages/*: no such file' error

### ISSUE THREAD

**Issue by jongwooo** [litmuschaos/litmus-helm#399]
When attempting to release Helm charts to GHCR (GitHub Container Registry), an error was occurring if there were no releases available, specifically showing the following error message:

```text
Error: .cr-release-packages/*: no such file
```

This issue arises when the expected directory for the release packages, `.cr-release-packages/*`, does not exist. To prevent this error and allow the action to gracefully handle cases where no charts are available for release, the following code snippet should be added:

```yaml
- name: Run chart-releaser
  id: chart-releaser
  # ...
- name: Push Charts to GHCR
  if: steps.chart-releaser.outputs.changed_charts
```

cc. @Jonsy13 @namkyu1999
