### ISSUE TITLE
Support custom configuration for worflow controller

### ISSUE THREAD

**Issue by Calvinaud** [litmuschaos/litmus-helm#405]
Hello,

At the moment, the only configuration that is inside the workflow-controller-configmap is:
```yaml
containerRuntimeExecutor: k8s
executor:
  imagePullPolicy: IfNotPresent
instanceID: xxx
```
It's possible to update the containerRuntimeExecutor but not the others configurations available in this configmap: https://argo-workflows.readthedocs.io/en/latest/workflow-controller-configmap/

The goal of this ticket is to support a custom workflow configuration.
Even when using: `useExistingWorkflowControllerConfigMap`, the configmap will overwritten by the helm-agent job.
